# Generated by Django 2.2.3 on 2019-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsessions', '0002_auto_20190805_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('BO', 'Bossa Nova'), ('LA', 'Latin'), ('SW', 'Swing'), ('LA/SW', 'Latin/Swing'), ('SND_LN', 'Second Line')], default='SW', max_length=10),
        ),
    ]
