# Generated by Django 2.2.3 on 2019-08-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsessions', '0003_auto_20190805_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tempo',
            name='appx_bpm',
            field=models.IntegerField(default=0),
        ),
    ]
