# Generated by Django 2.2.3 on 2019-08-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsessions', '0004_auto_20190805_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
